version: '3.8'

services:

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/ssl

  identity:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: identity
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      # Logging
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      # Certificates
      KC_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/certificates/potato.cld.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/certificates/potato.cld-key.pem
      # Hostname
      KC_HOSTNAME: identity.potato.cld
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8787:8787"
    command:
      - start-dev
      # - --features admin-fine-grained-authz
    volumes:
      - ./identity/keycloak/data:/opt/keycloak/data
      - ./certs:/opt/certificates

networks:
  default:
    name: identity-network
