version: '3.8'

services:

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./reverse-proxy/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certs:/etc/nginx/ssl
  
  database:
    image: mysql:8.0
    container_name: database
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./database/mysql/.env
      - ./identity/keycloak/database.env
    volumes:
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/init-scripts:/docker-entrypoint-initdb.d
    # environment:
      # MYSQL_ROOT_PASSWORD: root123
  
  identity:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: identity
    restart: unless-stopped
    env_file:
      - ./identity/keycloak/.env
      - ./identity/keycloak/database.env
    environment:
      # Logging
      KEYCLOAK_LOGLEVEL: INFO
      ROOT_LOGLEVEL: INFO
      # Certificates
      KC_HTTPS_PORT: 8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/certificates/potato.cld.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/certificates/potato.cld-key.pem
      # Hostname
      KC_HOSTNAME: identity.potato.cld
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8787:8787"
    command:
      - start
      # - --features admin-fine-grained-authz
    volumes:
      - ./identity/keycloak/data:/opt/keycloak/data
      - ./certs:/opt/certificates
    depends_on:
      - reverse-proxy
      - database

networks:
  default:
    name: identity-network
